/**
 * GET /api/test-presentation
 * Returns a test presentation generated by the Art Director Engine v2
 * For local testing only — loads from /tmp/test-presentation.json
 */

import { NextResponse } from 'next/server'

export const maxDuration = 30
import { readFileSync, existsSync } from 'fs'

export async function GET() {
  const path = '/tmp/test-presentation.json'
  if (!existsSync(path)) {
    return NextResponse.json({ error: 'Run: npx tsx scripts/test-engine.ts first' }, { status: 404 })
  }

  const data = JSON.parse(readFileSync(path, 'utf-8'))
  return NextResponse.json({ document: { id: 'test-local', title: 'CHERY Test', data: { brandName: 'CHERY', _presentation: data } } })
}
